### PR TITLE
update to version v1.0.0-rc.0

### PR DESCRIPTION
**Pull request by caillef**

### CODE REVIEW

**Comment by caillef** [comment]
@Larkooo here is the rc.0 version, I am currently testing it using the UE5 SDK, I'll let you know if anything is broken, but using the main.c, it seems to work well.

**Comment by Larkooo** [comment]
Ah thanks for the PR! It is lacking the WASM changes though, ok with closing this in favor of #64 which updates to rc.0 and adds support for historical messages to C and WASM? Otherwise you could make the changes on your side

**Comment by caillef** [comment]
Sure you can close this one!

**Comment by caillef** [comment]
closing this in favor of https://github.com/dojoengine/dojo.c/pull/64

**Pull request closed without merging**
